sudo: required
services:
    - docker

before_install:
    - docker build -t jangdonghyeon/docker-react -f Dockerfile.dev .

script:
    - docker run jangdonghyeon/docker-react npm run test -- --coverage
