sudo: required
services:
    - docker

before_install:
    - docker build -t jangdonghyeon/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jangdonghyeon/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: 'ap-northeast-2'
    app: 'docker'
    env: 'Docker-env'
    bucket_name: 'elasticbeanstalk-ap-northeast-2-344255633850'
    bucket_path: 'docker'
    on:
        branch: master
    access_key_id: '$AWS_ACCESS_KEY'
    secret_access_key:
        secure: '$AWS_SECRET_KEY'
